---
title: "Meta-analysis in R"
description: |
  Notes from Wolfgang's livestream
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r message=FALSE}
library(metafor)
library(tidyverse)
library(gt)

```

```{r}
dat <- dat.ishak2007

dat.long <- reshape(dat, direction="long", idvar="study", v.names=c("yi","vi"),
                    varying=list(c(2,4,6,8), c(3,5,7,9)))
dat.long <- dat.long[order(dat.long$study, dat.long$time),]
rownames(dat.long) <- 1:nrow(dat.long)
dat.long

# remove missing measurement occasions from dat.long
is.miss  <- is.na(dat.long$yi)
dat.long <- dat.long[!is.miss,]
rownames(dat.long) <- NULL
head(dat.long, 10)





```



```{r}

# construct the full (block diagonal) V matrix with an AR(1) structure
rho.within <- .97 # value as used by Ishak et al. (2007)
V <- lapply(split(with(dat, cbind(v1i, v2i, v3i, v4i)), dat$study), diag)
V <- lapply(V, function(v) sqrt(v) %*% toeplitz(ARMAacf(ar=rho.within, lag.max=3)) %*% sqrt(v))
V <- bldiag(V)
V <- V[!is.miss,!is.miss] # remove missing measurement occasions from V
V[1:10,1:10]

```


```{r}
dat <- dat.long
# multivariate model with heteroscedastic AR(1) [HAR] structure for the true effects
res1 <- rma.mv(yi, V, mods = ~ factor(time) - 1, random = ~ time | study,
               struct = "HAR", data = dat)
print(res1, digits=2)



```

