---
title: "it ain't just you, grrl"
description: |
  The dark side of open science.
author:
  - name: Charles T. Gray
    url: https://github.com/softloud/onetimetrophybitch
date: 07-22-2020
output:
  distill::distill_article:
    self_contained: false
categories:
  - grrr...
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

A friend, from a programming network (for women and minorities) I belong to, sent me a few resources recently. Before I lose the clarity with which I can synthesise these resources, I am writing this down. The three resources I'll draw on in this post are:

- [Trashing](https://www.jofreeman.com/joreen/trashing.htm) -- Joreen
- [Stop 'Playing' Diversity Games with People of Color](https://medium.com/@monicafcox/stop-playing-diversity-games-with-people-of-color-659dc995a4bf) -- Cox
- [Canceling](https://www.youtube.com/watch?v=OjMPJVmXxV8&feature=youtu.be) vlog -- Contrapoints. Long, but worth it. 

<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/OjMPJVmXxV8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->

I wrote to a few very prominent women in mathematical science about trashing, and one observed that trashing happens to both men and women. That it is a social phenomenon whereby anyone who stands out, is noncomformist in any way, is punished by the very structures that should be there to protect them. 

Trashing and canceling are equivalent terms, in essence. For Contrapoints, this was about the trans and (new term for me) **truscum** (transmedicalists) communities. For Joreen, second-wave feminism. Another woman sent me her reminiscences of the eighties and the antinuclear movement. 

I write this down to add to what I discover to be a decades-long (no doubt longer) story. To add another rumination, to this body of trashed lit. I write this down for my future self, for the grrl who sits there thinking she must be a terrible, horrible person, for the people she admires the most to think so of her. For the next time I wonder.

**It ain't just you, grrl.** 

But that ain't gonna stop 'em thinking it is. Never forget that. When people show you how they feel entitled to treat you, to abuse you, believe them. Here's why.

What sits at the heart of the violence of trashing, is **essentialism**:

> Essentialism is when we go from criticizing a person's actions to criticizing the person themselves. We're not just saying they did bad things. We’re saying they’re a bad person.  -- Contrapoints

Joreen observes that the key identifier for trashing is essentialism.

> The acid test, however, comes when one tries to defend a person under attack, especially when she's not there, If such a defense is taken seriously, and some concern expressed for hearing all sides and gathering all evidence, trashing is probably not occurring. But if your defense is dismissed with an oft-hand "How can you defend her?"; if you become tainted with suspicion by attempting such a defense; if she is in fact indefensible, you should take a closer look at those making the accusations. There is more going on than simple disagreement. -- Joreen

What **trashing** actually is, well, the hard thing about defining it is that it is *defined by absence*. How did Joreen know she'd been trashed? By the voiding of her very existence within a cultural group.

>  My departure was very quiet. I told two people, and stopped going to the Women's Center. The response convinced me that I had read the message correctly. No one called, no one sent me any mailings, no reaction came back through the grapevine. Half my life had been voided, and no one was aware of it but me. -- Joreen

After six weeks' sustained pestering from someone last year, where in each instance, I carefully explained their demands distressing, only to have the very behaviours I carefully described as most distressing enacted over and over again. At the time, I likened this experience to emotional rape. I felt and do feel violated. 

> Trashing is a particularly vicious form of character assassination which amounts to psychological rape. It is manipulative, dishonest, and excessive. It is occasionally disguised by the rhetoric of honest conflict, or covered up by denying that any disapproval exists at all. But it is not done to expose disagreements or resolve differences. It is done to disparage and destroy. -- Joreen

And, based on the lack of remorse, I am left to conclude it was spite. As Contrapoints notes, this is a common practice of trashing. For every declaration that some prominent peson of minoritised status is a terrible person who should be canceled, trace it back you'll find a "controversy manufactured from the top by a handful of seemingly vindictive and envious people". They will present it as a moral argument, with themselves in the right.

> But moralism or intellectualism provide a phony pretext for the call-out. You can pretend you just want an apology; you can pretend you're just a “concerned citizen” who wants the person to improve. You can pretend you're simply offering up criticism, when what you're really doing is attacking a person's career and reputation out of spite, envy, revenge. It could be any motivation. -- Contrapoints 

It felt as if open season had been declared on me, and each and every person who wielded any power in my life seemed determined to teach me a lesson. 

There was the supposed-friend I turned to for emotional support at a conference when a man was invading my professional space, who then told several people without my permission and initiated Code of Conduct proceedings when I had explicitly requested no such action be taken. 

_A part of me is still apoplectic at this. Are you fucking kidding me? I knew what would happen, how damaging that would be for me, and all of my worst fears were realised._ 

There was the person who felt it was their six-week long crusade to _teach_ me I was wrong about the complexity of their organisations reimbursement procedure. Now I understand, this was not isolated, but the tired mechanisms of trashing playing out once again. People are motivated by a desire to take the seemingly prominent person down a peg (Contrapoints). It's not a big deal. It's just a little thing. To them. For the recipient, it's a relentless barrage.  

Then there are the people who recoil from association. As Contrapoints observes, canceling has a transitive property, whereby others cannot interact with the canceled. I can only but assume this was the unspoken belief of my co-author, who, when I confronted him for talking to me for hours by direct message but not associating with me in public, pretended he was "teaching me a lesson" and "toughening me up". Archly, I retorted why I woman of colour who's educated herself off the streets, recovered from multiple beatings and rapes, needed to be toughened up?  

It's dangerous when the very structures that are meant to be in a place to protect minoritised people are wielded to hurt them. Minoritised people will seek out these networks, as Joreen did with feminism, and Contrapoints with trans twitter. It makes sense that those who epitomise minoritised tropes (trans, gay, coloured, poor, pick a thing) in others' eyes, may rise to prominence in these communities. And thus it's seen as *punching up* to someone with greater social capital. 

These microagressions accumulate, both Contrapoints and Joreen describe suicides and breakdowns than have resulted from trashing. 

I am heartened to see the groundswell of Black Lives Matter protests around the world. However, it also terrifies me. Many well-intentioned organisations will create grants, opportunities targeting people of colour, minoritised people. And I deeply fear these people will not consider that the people they are trying to reach will likely interact with lower-level people from their organisation. People wtih an axe to grind, people who do not enjoy their administrative task, and those who quite fairly resent their working conditions. 

I worry there is no recognition that it is the minoritised who run the  gauntlet of these new initiatives, placing themselves at the mercy of petty-minded people who who shirk not from wielding their small power to take the minoritised person down a peg. At every turn, it is the  minoritised who shoulder the risk. 

If the organisation is not guarding against this, and does not recognise that institutional abuse (using institutionl systems to abuse, such as reimbursement or CoC) is *abuse* is **playing diversity**.

> When I am blamed for disrupting a system that wasn’t built for me and am expected to fix that system in the same breath, leaders in an organization are not being accountable for their roles in this system. They are playing diversity.

Indeed, with the reimbursement, the six weeks' harassment punctuated by the entirely predictable losing of my patience, I explicitly began this exchange by saying I was letting them know *as a courtesy*. It is curious to me how entitled people who are paid to do a job feel to my unpaid time. Yes, I am grateful for opportunities and grants. But if I am spending weeks, months, and indeed years in this case, on a task such as a reimbursement, it's not really a freely given grant now is it? In the end, despairing we were 12 months from me identifying they were one character in a string out from providing said reimbursement, I had no choice but to give up, and forfeit the substantial amount we'd fronted. 

But, here's the thing. My interests are in mathematics, programming, scientific practice, and evidence synthesis. If someone is playing games with me, they're not interested in my science. 

>  Dr. Maya Angelou writes, “When people show you who they are, believe them the first time.” Your job is not to be a martyr but to do your job, especially since you will be evaluated as such. Educate people once, twice, maybe three times if you are patient. At some point, if you are educating and talking, yet people are not listening or are not able or willing to facilitate change, you have to try a new strategy. This may include changing the circle in which you engage or transitioning to a different environment. Abuse (as you define it for yourself) is not acceptable, and if you experience it, do something to protect yourself. If you leave your job next week, you will be replaced quickly. Your well-being, however, is not so easy to replace. Remember, your job description does not require you to become a martyr for your job. -- Cox

So, I'm going to seek out those who are interested in me as a scientist, and as a thinker. I have so many people like that in my life already, I am choosing to focus on them. 

And now that I recognise the social mechanism of trashing, and have documented my clarity of thought on this, hopefully next time - and there *will* be a next time for a flamboyant woman of colour in mathematical science - next time I will believe the person someone is *showing* themselves to be. No matter their professed diversity values. 

And I'll remember that every pedestal that someone's tried to topple me from was a pedastal that *they put me on*. 

My goals in life? I wanted to read and be educated, do work that I find fulfilling, in mathematical science, of some description. In particular, not be a piano teacher; I want a better standard of life. I have already achieved the goal of buying a property in an idyllic remote location and nesting with my lovely husband (for us isolation has been romantic and conflict free). 