---
title: "the door is right in front of me, all i need do is walk through it"
description: |
  A rumination on stopping smoking. 
author:
  - name: Charles T. Gray
    url: https://github.com/softloud/onetimetrophybitch
date: 02-27-2020
output:
  distill::distill_article:
    self_contained: false
categories: 
    - grrr...
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<div class="tenor-gif-embed" data-postid="10227362" data-share-method="host" data-width="50%" data-aspect-ratio="1.7913669064748199"><a href="https://tenor.com/view/smoking-cigarette-drag-smoke-cig-gif-10227362">Smoking Cigarette GIF</a> from <a href="https://tenor.com/search/smoking-gifs">Smoking GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>

***

Smoking is a socially legitimised form of self harm. Writing this is the 
hundredth thousandth try to stop. But rationally, I know, the defining feature
of the final time is that it really will be final.

Smoking has become the last vestige of my destructive behaviours; a device to 
fill the void left in me when I left my parents' house at fifteen, and hit the
streets. The trauma of the compromises one makes, leading to a loss of 
sense of self, are hard to describe to others, it is too intersectional. But 
the consequences are lifelong. My husband read in the paper the other day
that only one per cent of children in taken into state care attend university.
Complex post-traumatic stress is why. 

To find myself, I have played concert halls and performing arts centres. I have 
researched culture, music, film, mathemathics, science, and computation. I have 
backpacked, and read literary canon.

I have composed, I have been composed, I have been *decidedly* not composed. 

I have found work that is fulfilling, that I'm competent enough at, that the
world needs; I have found *ikigai* in this post-capitalist still-patriarchal
society. 

***

And yet, I struggle with smoking.

I force myself into self harming patterns with it. I stop, only to start again,
on some preemptive stressor. Really, I am punishing myself for having a 
different reaction to a situation than others around me.

I buy packs of cigarettes. Then I convince myself I have stopped. Then I throw
them in the bin. Then I come back a day later and fish them out of the bin.

It is disgusting. It is pathetic. 

But it's nothing compared to how pathetic things were. 

When I was fifteen I was living in a squat in *some place I can't remember* with 
*I don't remember who at all*. Perhaps it was Albert Park, a ritzy Melbourne
suburb where we squatted in an abandonend development. Despite only being 
halfway constructed, it had a functional toilet, and, rather suprisingly, 
electricity. It was very comfortable, as squats go. We abandoned it when the
nazi punks came by while we weren't around and stole our shit. 

Anyways, I was staying there. We were so poor; we were completely accustomed
to not eating much. However this was ameliorated by chain smoking. 

Out of all my pathetic moments of smoking, I believe this was the lowest. I 
recall being at a bus stop with my fellow squatters, in the pre-dawn light, 
before commuters arrived. This was before smoking was banned at public 
transport waiting places. 

We collected butts from the ground, took them home, and rerolled them. 

Fast forward to now, and I feel like I am reliving that moment, every time
I fish cigarettes out of the bin. 

***

One of the glorious things about being a specialist piano teacher was meeting 
the kind of people who valued such things. One of my student's parents was a
substance abuse specialist, having just completed a doctorate. We'd chat as the
student packed up. She confirmed
what I'd always believed, that substance abuse is defined symptomatically,
not categorically. 

Nor is it even empirical. We do not hear with such cavalier frequency
of careless weed-influenced drivers
killing people or flying into a jealous rage, as reportage so often ties to
alcohol. If it were empircal, we'd be controlling alcohol far more than weed.

I've recently been combining music therapy with yoga to process past trauma.
I no longer need something as destructive as cigarettes in my life. The 
physical lethargy is anathema to research productivity, and research is my 
happiest place. 

Smoking has been a feature of my life since I was fourteen years old. And it 
has always been an act of self harm. It tastes awful, there is no pleasure,
and it gives me a headache. It served a social purpose when I needed it, but it
no longer benefits me in any way. In fact, it is the most harmful thing I do
to myself. 

The problem with socially legitimised forms of self harm is that we pretend they
are somehow easier than socially unacceptable forms of self harm. I have known 
many people who have cut themselves for a time, as a form of processing trauma. 
With socially unacceptble forms of self harm, they are still primarily *coping* 
mechanisms.

What makes overcoming a harmful coping mechanism difficult is the extremity
of the instigating factors. In my case, these are the extreme poverty and 
neglect I experienced as an adolescent. 

The trick, I believe, is to provide myself with enough helpful coping 
mechanisms, as opposed to harmful ones, such that I do not require the harmful
coping mechanisms anymore. I have amassed a multitude, I am publishing papers, 
I have made close friends. 

The door is right in front of me, all I need do is walk through it.

> Go be awesome 

Says \@djnavarro to **me**, all the damn time. Makes me feel like a super hero,
it does.

***

I gathered all the butts, papers, and accoutrements in a plastic bag, tied 
a definitive knot. 

And somehow, in that disgusting bag of butts and ash feels so much 
emotional trauma I've associated with that. 

I aim to be okay this time, knowing it's sitting there in the bin, 
a filthy plastic bag
of headache-inducing, foul-smelling ash. Soon enough rubbish
collection will come take it away, and all that will remain will be a fading
memory of something that used to bother me but just doesn't, now.